---
# handlers file for web
- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: start php-fpm
  service:
    name: php8.1-fpm
    state: started
    enabled: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
