---
# tasks file for web
- name: Install Nginx
  apt:
    name: nginx
    state: latest
  notify:
    - start nginx

- name: Install php-fpm
  apt:
    name: php8.1-fpm
    state: present
  notify:
    - start php-fpm

- name: Ensure document_root exists
  file:
    path: "{{ document_root }}"
    state: directory

- name: Deploy website
  copy:
    src: "index.php"
    dest: "{{ document_root }}"

- name: Update Nginx config
  template:
    src: "default.j2"
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx
