---
# handlers file for php-fpm
- name: start php-fpm
  service:
    name: php8.1-fpm
    state: started
    enabled: yes

- name: restart php-fpm
  service:
    name: php8.1-fpm
    state: restarted
